package www.affaxerd.recyclerviewapplication;


public class Item {
    //THIS IS THE MODEL CLASS
//step 1. create variable that will represent the data of all the items
    String name;
    String email;
    Integer image;

 //step 2: create a constructor. (generated by intellij)


    public Item(String name, String email, Integer image) {
        this.name = name;
        this.email = email;
        this.image = image;
    }



//step 3: create getters(setters not necessary) (also generated by intellij.)


    public String getName() {
        return name;
    }

    public String getEmail() {
        return email;
    }

    public Integer getImage() {
        return image;
    }
}
